import type { Metadata } from "next";
import { Header } from "@/app/_components/Header/Index";
import "./globals.css";
import { Lexend } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lexend = Lexend({
  weight: ["100", "300", "400", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={lexend.className}>
      <body className={"antialiased"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
